<?php echo $this->Partial('index/tpl/header.phtml', array(
	'cssList' =>'/my/my.css'		
))?>
<?php 
	echo $this->Partial('my/tpl/nav.phtml', array('cpage'=>'account'));
	$cuser = $this->v['cuser'];
	echo $this->Partial('my/account/tpl/nav.phtml', array('cpage' => 'password'));
?>
<h2 class="title">修改密码</h2>
<form method="post" action="/my/account/_password" id="formUpdate">
<dl class="my_dl g">
	<dt>当前密码</dt>
	<dd><input type="password" name="oldPassword" style="width:100px;" verify-rule="{required:'当前密码不能为空'}"/></dd>
	<dt>新密码</dt>
	<dd><input type="password" name="password" id="txtPassword" style="width:100px;" verify-rule="{
				required:'请输入密码',
				range:{
					event:['blur'],
					type:'length',
					min:6,
					max:20,
					msg:'密码长度为6-20位',
					trigger:'rePassword.compare'
				}
			}"/></dd>
	<dt>邮箱</dt>
	<dd><input type="password" name="rePassword" style="width:100px;" verify-rule="{
				compare:{
					event:'blur',
					to:'txtPassword',
					condition:'equal',
					msg:'两次输入密码必须一样',
					name:'rePassword.compare'
				}
			}"/></dd>
	<dt></dt>
	<dd><input type="submit" value="确定"/></dd>
</dl>
</form>
<script>
hapj.get('errMap').add({
	'user.u_oldPasswordWrong': '当前密码错误'
});
hapj.com('verify').active('formUpdate', {
	ok:function(){
		hapj.ui.dialog.ok('修改成功', function(){location.reload();})
	}
});</script>
<?php echo $this->Partial('index/tpl/footer.phtml')?>